// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCekwtzhENxfoxbMdpJvhvZAj7QodIDMEA',
    appId: '1:971477337144:web:1ad9e2cb31f440c06d92cd',
    messagingSenderId: '971477337144',
    projectId: 'authtutorial22',
    authDomain: 'authtutorial22.firebaseapp.com',
    storageBucket: 'authtutorial22.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD__oT2tLs_rP9wTpc2Sph9QGa01_kzPho',
    appId: '1:971477337144:android:04806cf01b4fd0446d92cd',
    messagingSenderId: '971477337144',
    projectId: 'authtutorial22',
    storageBucket: 'authtutorial22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5vEMA6UO0cXxMaKYNN3xV3rC6GMmdPM8',
    appId: '1:971477337144:ios:733dcad7caa6c7e46d92cd',
    messagingSenderId: '971477337144',
    projectId: 'authtutorial22',
    storageBucket: 'authtutorial22.appspot.com',
    iosBundleId: 'com.example.exerciseLoginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5vEMA6UO0cXxMaKYNN3xV3rC6GMmdPM8',
    appId: '1:971477337144:ios:733dcad7caa6c7e46d92cd',
    messagingSenderId: '971477337144',
    projectId: 'authtutorial22',
    storageBucket: 'authtutorial22.appspot.com',
    iosBundleId: 'com.example.exerciseLoginPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCekwtzhENxfoxbMdpJvhvZAj7QodIDMEA',
    appId: '1:971477337144:web:f443ffdfc42033926d92cd',
    messagingSenderId: '971477337144',
    projectId: 'authtutorial22',
    authDomain: 'authtutorial22.firebaseapp.com',
    storageBucket: 'authtutorial22.appspot.com',
  );
}
